config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :listings do
    resources :portions
  end
  

  root 'welcome#index'

  get '/listings/:id/finalize', to: 'listings#finalize', as: 'complete'

  get '/my_listings', to: 'listings#user_index', as: 'user_index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates :product, presence: true
	validates :required_amount, :bulk_cost, numericality: {greater_than: 0}


	has_many :portions
	has_many :users, through: :portions

end

app/models/portion.rb
class Portion < ActiveRecord::Base
	validates :share, numericality: {greater_than_or_equal_to: 0}

	belongs_to :user
	belongs_to :listing

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :login

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  # def email_required?
  # 	false
  # end

  # def email_changed?
  # 	false
  # end

  validates :username, uniqueness: true

  has_many :portions, dependent: :destroy
  has_many :listings, through: :portions, dependent: :destroy

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions.to_hash).first
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!, except: :index
  before_action :configure_permitted_parameters, if: :devise_controller?

  def disable_nav
    @disable_nav = true
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :phone_number, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :phone_number, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :phone_number, :password, :password_confirmation, :current_password) }
  end
  

  private 

    def total_claimed(portions)
  	 sum = 0
  	   portions.each do |portion|
  	     sum += portion.share
  	   end
  	 sum
    end 

    def total_claimed_minus_self(portions, mine)
     sum = 0
       portions.each do |portion|
         sum += portion.share
       end
     sum - mine.share
    end 

    def cost_per_person(listing, shares_of_person)
      (((listing.bulk_cost / listing.required_amount.to_f) * shares_of_person) * 100).ceil / 100.0
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
	before_action :check_owner, only: [:edit, :update, :destroy]

	def index
		@listings = Listing.all.order(created_at: :desc)
	end

	def new
		@listing = Listing.new
	end

	def create
		@listing = current_user.listings.build(listing_params)
		@listing.owner = current_user.username
		
		if @listing.save 
			redirect_to new_listing_portion_path(@listing)
		else
			render :new
		end		

	end

	def show
		@listing = Listing.find(params[:id])
		@portions = @listing.portions

		@remaining = @portions[0].listing.required_amount - total_claimed(@portions)

		@owns = false
		if @listing.owner == current_user.username
			@owns = true
		end

		@joined = false
		@this_portion = current_user.portions.where(listing_id: params[:id]).first
		if @this_portion.present?
			@joined = true
		end

		@unit_cost = ((@listing.bulk_cost / @listing.required_amount.to_f) * 100).ceil / 100.0

	end

	def edit 
		@listing = current_user.listings.find(params[:id])
	end

	def update
		@listing = current_user.listings.find(params[:id])

		if @listing.update(listing_params)
			redirect_to listing_path(@listing)
		else
			render :edit
		end
	end

	def destroy
		@listing = Listing.find(params[:id])
		@listing.destroy
		redirect_to listings_path
	end

	def finalize

		@listing = Listing.find(params[:id])

		@owns = false
		if @listing.owner == current_user.username
			@owns = true
		end

		@joined = false
		@this_portion = current_user.portions.where(listing_id: params[:id]).first
		if @this_portion.present?
			@joined = true
		end
		
		@unit_cost = ((@listing.bulk_cost / @listing.required_amount.to_f) * 100).ceil / 100.0
		@users_to_costs = {}
		@listing.users.each do |user|
			costperperson = cost_per_person(@listing, user.portions.where(listing_id: params[:id]).first.share)
			@users_to_costs[user] = costperperson
		end
	end

	def user_index
		@listings = Listing.where(owner: current_user.username)
	end


	private

		def listing_params
			params.require(:listing).permit(:product, :required_amount, :bulk_cost)
		end

		def check_owner
  		unless current_user.username == Listing.find(params[:id]).owner
  			flash[:alert] = "You must have created the listing in order to edit or delete it."
  			redirect_to listing_path(params[:id])
  		end
  	end

end

app/controllers/portions_controller.rb
class PortionsController < ApplicationController
	before_action :check_owner, only: [:edit, :update, :destroy]

	def index
		@listing = Listing.find(params[:listing_id])
		@portions = Portion.where(listing_id: params[:listing_id])
	end

	def new
		@listing = Listing.find(params[:listing_id])
		# MAYBE DON'T NEED THIS
		@portion = Portion.new
		@portions = @listing.portions
		@remaining = @listing.required_amount - total_claimed(@portions)
	end

	def create
		@listing = Listing.find(params[:listing_id])
		@new_portion = @listing.portions.build(portion_params)
		@new_portion.user_id = current_user.id
		@portions = @listing.portions
		@remaining = @listing.required_amount - total_claimed(@portions)

		if @new_portion.save
			redirect_to listing_path(@listing)
		else
			render :new	
		end
	end

	def edit
		@listing = Listing.find(params[:listing_id])
		@portion = current_user.portions.find(params[:id])
		@portions = @listing.portions
		@my_portions = current_user.portions.where(listing_id: params[:listing_id]).first
		@remaining = @listing.required_amount - total_claimed_minus_self(@portions, @my_portions)
	end

	def update
		@listing = Listing.find(params[:listing_id])
		@portion = current_user.portions.find(params[:id])

		@portions = @listing.portions

		if @portion.update(portion_params)
			redirect_to listing_path(@listing)
		else
			render :edit
		end
	end

	def destroy
		@portion = Portion.find(params[:id])
		@portion.destroy
		redirect_to listing_path(params[:listing_id])
	end

	private

		def portion_params
			params.require(:portion).permit(:share)
		end

		def check_owner
  		unless current_user.id == Portion.find(params[:id]).user_id
  			flash[:alert] = "You must have created the portion in order to edit or delete it."
  			redirect_to listing_path(params[:id])
  		end

  	end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :disable_nav, only: [:index]

	def index
		@listings = Listing.all.order(created_at: :desc)
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_alerts.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_nav.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top navbar-shrink navbar-all-pages">
        <div class="fluid container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
<!--                 <a class="navbar-brand page-scroll" href="/#page-top">Save With Me</a> -->
                <%= link_to "Save With Me", root_path(:anchor => 'page-top'), :class => "navbar-brand page-scroll" %>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
<!--                         <a href="#page-top"></a> -->
                        <%= link_to "", root_path(:anchor => 'page-top'), :class => "page-scroll" %>
                    </li>
                    <li>
                        <%= link_to "What Is Save With Me?", root_path(:anchor => 'intro'), :class => "page-scroll" %>
                    </li>

                    <% if user_signed_in? %>

                   	 	<li>
                            <%= link_to "Local Listings", listings_path, :class => "scroll-link" %>
                        </li>
                        <li>
                            <%= link_to "My Listings", user_index_path, :class => "scroll-link" %>
                        </li>
	                    <li class="dropdown">
	                      	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><strong><%= current_user.username %></strong> <span class="caret"></span></a>
	                          <ul class="dropdown-menu" role="menu">
	                            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
	                            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
	                          </ul>
	                    </li>

                    <% else %>
                      <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li> 
                      <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Save With Me</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>
</head>
<body id="page-top" class="index">
  
  <%= render 'layouts/nav' unless @disable_nav %>
  <%= render 'layouts/alerts' %>

  <%= yield %>
  
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</body>
</html>

app/views/listings/_form.html.erb
<% if @listing.errors.present? %>
	<% @listing.errors.full_messages.each do |msg| %>
		<p style="color: red"><b><%= msg %></b></p>
	<% end %>
<% end %>

<%= form_for @listing do |f| %>
	<p><%= f.label :product %></p>
	<p><%= f.text_field :product %></p>

	<p><%= f.label :required_amount %></p>
	<p><%= f.text_area :required_amount %></p>

	<p><%= f.label :bulk_cost %></p>
	<p><%= f.text_area :bulk_cost %></p>

	<%= f.submit :next %>
<%end%> 

app/views/listings/edit.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>Editing a listing</h1>

    <%= render 'layouts/nav' %>
    <%= render 'form' %>
  </div>
</div>

app/views/listings/finalize.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>Finalize your save on <%= @listing.product %></h1>

    <div style="text-align: center;"><p>The bulk price for <%= pluralize(@listing.required_amount, 'share') %> of <%= @listing.product.pluralize %> is R<%= @listing.bulk_cost %>.</p>
    <p>With this deal, the unit price for 1 share is R<%= @unit_cost %>. </p></div>

    <hr>

    <h3>Share breakdown:</h3>

    <div style="text-align: center;"><%= render partial: 'portions/portion', collection: @listing.portions %></div>

    <hr>

    <h3>Cost breakdown:</h3>

    <% @users_to_costs.each do |user, cost| %>
    	<div style="text-align: center;"><p><%= user.username %> should pay R<%= cost %> for <%= pluralize(user.portions.where(listing_id: params[:id]).first.share, 'share') %> of <%= @listing.product %></p></div>
    <% end %>
  </div>
</div>

app/views/listings/index.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>Listings in My Area</h1>

	<% @listings.each do |listing| %>
		<p style="font-size: 20px; text-align: center;"><%= link_to listing.product, listing_path(listing) %></p>
	<% end %>

	<p class="btn-xl" style="margin: 0 auto; width: 400px;font-size: 25x; text-align: center;"><%= link_to 'Create a New Listing', new_listing_path, class: "page-scroll btn-xl", style: "color: black;" %></p>

</div>
</div>

app/views/listings/new.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">

    <h1> Create a Listing </h1>

    <%= render 'form' %>

    <%= link_to 'Back', listings_path %>

  </div>
</div>

app/views/listings/show.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>Saving on <%= @listing.product %></h1>

    <% if @owns %>
      <p>
        <%= link_to 'Edit Listing', edit_listing_path(@listing) %>&nbsp;|&nbsp;
        <%= link_to 'Delete Listing', listing_path, method: :delete, data: {confirm: 'Are you sure?'} %>
      </p>
    <% end %>

    <p style="font-size: 20px; text-align: center;">The bulk price for <%= pluralize(@listing.required_amount, 'share') %> of <%= @listing.product.pluralize %> is R<%= @listing.bulk_cost %>.</p>
    <p style="font-size: 20px; text-align: center;">With this deal, the unit price for 1 share is R<%= @unit_cost %>.</p>



    <hr>

    <p style="font-size: 20px; text-align: center;"><%= pluralize(@remaining, 'more share') %> available!</p>

    <% if @remaining == 0 %>
        <p class="btn-xl" style="margin: 0 auto; width: 400px; font-size: 25x; text-align: center;">
          <%= link_to "Finalize purchase!", complete_path(params[:id]), class: "page-scroll btn-xl", style: "color: black;" %>
        </p>
    <% end %>

    <% if !@joined %>
     <p class="btn-xl" style="margin: 0 auto; width: 400px; font-size: 25x; text-align: center;">
       <%= link_to "Save with me!", new_listing_portion_path(params[:id]), class: "page-scroll btn-xl", style: "color: black;" %>
       </p>
     <% end %>

    <h3>Current shares claimed:</h3>

    <div style="text-align: center;"><%= render partial: 'portions/portion', collection: @listing.portions %></div>


    <p style="text-align: center;"><%= link_to 'Back to Local Listings', listings_path %></p>
  </div>
</div>

app/views/listings/user_index.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>My Listings</h1>

    <% @listings.each do |listing| %>
      <p style="font-size: 20px; text-align: center;"><%= link_to listing.product, listing_path(listing) %></p>
     <% end %>

     <p class="btn-xl" style="margin: 0 auto; width: 400px;font-size: 25x; text-align: center;"><%= link_to 'Create a New Listing', new_listing_path, class: "page-scroll btn-xl", style: "color: black;" %></p>
  </div>
</div>

app/views/portions/_form.html.erb
<%= form_for [@listing, @portion] do |f| %>
	<%= f.select :share, 1..@remaining %>

	<%= f.submit :submit %>
<%end%>

app/views/portions/_portion.html.erb
<p>
  <%= portion.user.username %> claimed <%= pluralize(portion.share, 'share') %>.


   <% if portion.user.username == current_user.username %>
 <!--      <p style="font-size: 20px; text-align: center;"> -->
        <%= link_to 'Edit Share', edit_listing_portion_path(@listing, @this_portion) %> &nbsp;|&nbsp;
        <%= link_to 'Delete Share', listing_portion_path(@listing, @this_portion), method: :delete, data: {confirm: 'Are you sure?'} %>
      <!-- </p> -->
    <% end %>

</p>

app/views/portions/edit.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>Editing Your Shares</h1>

    <p>You currently are signed up to claim <%= @portion.share %> shares.</p>

    <p>Please enter how many total shares you would like.</p>

    <p>Desired total shares:</p>

    <%= form_for [@listing, @portion] do |f| %>
    	<%= f.select :share, 1..@remaining %>

    	<%= f.submit :submit %>
    <%end%>
  </div>
</div>

app/views/portions/index.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>Shares claimed:</h1>

    <%= render partial: 'portion', collection: @portions %>

    <%= link_to "Back to Listing", listing_path(@listing.id) %>
  </div>
</div>

app/views/portions/new.html.erb
<div class="container">
  <div class="push_down_content_bc_nav">
    <h1>Claim Your Shares</h1>

    <p>How many shares of <%= @listing.product.pluralize %> would you like?</p>

    <%= render 'form' %>
  </div>
</div>

app/views/users/shared/_links.html.erb
<div class="container">
<div class="push_down_content_bc_nav">

<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

</div>
</div>

app/views/welcome/_nav.erb
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-homepage navbar-fixed-top">
        <div class="fluid container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Save With Me</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#intro">What is Save With Me?</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#ready">Ready to Save?</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#team">Our Team</a>
                    </li>

                    <% if user_signed_in? %>

                   	 	<li>
                            <a class="scroll-link" href="/listings">Local Listings</a>
                        </li>

	                    <li class="dropdown">
	                      	<a href="#" class="dropdown-toggle" data-toggle="dropdown" type="button" aria-expanded="false"><strong><%= current_user.username %></strong> <span class="caret"></span></a>
	                          <ul class="dropdown-menu" role="menu">
	                            <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
	                            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
	                          </ul>
	                    </li>

                    <% else %>
                      <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li> 
                      <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

app/views/welcome/index.html.erb
<%= render 'nav' %>
    <!-- Header -->
    <header>
        <div class="container">
            <div class="intro-text">
                <div class="intro-lead-in">Community-Based Sharing & Saving</div>
                <div class="intro-heading">Save With Me</div>
                <a href="#intro" class="page-scroll btn btn-xl">Tell Me More</a>
            </div>
        </div>
    </header>

    <!-- Intro Section -->
    <section id="intro">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">What is Save With Me?</h2>
                    <h3 class="section-subheading text-muted">Save With Me is an integrated platform for mobilizing members of a community around the shared goal of resource conservation. <br><br> Users can create their own shopping lists and join those of others in their area to exploit the power of bulk buying.<br> </h3>
                </div>
            </div>
            <div class="row text-center">
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-money fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="intro-heading">Saving You Money</h4>
                    <p class="text-muted">By allowing users to pool together resources to buy products in bulk, Save With Me helps individuals access wholesale prices as a cost-saving alternative to buying smaller quantities, which are often more costly per unit. This not only reduces the cost of commonly-needed products, but it also increases the accessibility of products that may otherwise be unattainable.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-clock-o fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="intro-heading">Saving You Time</h4>
                    <p class="text-muted">Through the in-app communication system and optional secure payment service, members of a finalized listing can coordinate on the logistics for completing their purchase. Post-purchase analytics will log each user's experience, allowing them to crowdsource future recommendations, contribute to the existing database of local bulk deals, and visualize their overall savings.</p>
                </div>
                <div class="col-md-4">
                    <span class="fa-stack fa-4x">
                        <i class="fa fa-circle fa-stack-2x text-primary"></i>
                        <i class="fa fa-shopping-cart fa-stack-1x fa-inverse"></i>
                    </span>
                    <h4 class="intro-heading">Saving You Effort</h4>
                    <p class="text-muted">While empowering users to take advantage of the money-saving quality of bulk purchasing, Save With Me simultaneously provides an avenue to circumvent other issues blocking access to products. Coordination on payment and purchasing, for instance, creates potential solutions to impasses such as transportation limitations, lack of time, or unawareness of bulk deals.</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Ready to Save Section -->
    <section id="ready" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Ready To Save? </h2><br>
                    <img src="../img/path-to-sun.jpg">
                    <h3 class="section-subheading" style="font-size: 26px;"><br><%= link_to "Join the Save With Me community and browse listings in your area!", listings_path %><br><br></h3>
                    
                    
                </div>
            </div>
        </div>
    </section>

    <!-- Team Section -->
    <section id="team" class="bg-light-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="section-heading">Our Team</h2>
                    <h3 class="section-subheading text-muted">Going strong since July 2015!</h3>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-2"></div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="img/team/kleo.png" class="img-responsive img-circle team-icons" alt="">
                        <h4>Kleo Greenwood</h4>
                        <p class="text-muted">2013kgreenwood@gmail.com</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="https://twitter.com/basedkelp"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com/actuallykph"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="http://www.neopets.com/userlookup.phtml?user=therealkleo"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="team-member">
                        <img src="img/team/aobo.png" class="img-responsive img-circle team-icons" alt="">
                        <h4>Aobo Guo</h4>
                        <p class="text-muted">aobo.guo@gmail.com</p>
                        <ul class="list-inline social-buttons">
                            <li><a href="#"><i class="fa fa-twitter"></i></a>
                            </li>
                            <li><a href="https://www.facebook.com/aobo.s.guo"><i class="fa fa-facebook"></i></a>
                            </li>
                            <li><a href="https://www.linkedin.com/pub/aobo-guo/a5/403/b10"><i class="fa fa-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-2"></div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <p class="large text-muted">This is our first app together!</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Clients Aside -->
    <aside class="clients">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <a href="#">
                        <img src="img/logos/ix_logo.png" class="img-responsive img-centered" alt="">
                    </a>
                </div>
                <div class="col-md-6 col-sm-6">
                    <a href="#">
                        <img src="img/logos/brian-logo.png" class="img-responsive img-centered" alt="">
                    </a>
                </div>
            </div>
        </div>
    </aside>

    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <span class="copyright">Copyright &copy; Save With Me 2015</span>
                </div>
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <ul class="list-inline quicklinks">
                        <li><a href="#">Privacy Policy</a>
                        </li>
                        <li><a href="#">Terms of Use</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>